/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package blackjack;

import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Erick Garcia
 */
public class BlackJackGameD extends javax.swing.JFrame {

    String playerName;
    String dealerName;
    String playerCards;
    int playerScore;
    String dealerCards;
    int dealerScore;
    BlackJack game;
    boolean isPlayer;
    boolean isDealer;
    private ArrayList<String> playerCardsArr;
    private ArrayList<String> dealerCardsArr;
    private ArrayList<JLabel> playersHandGUI;
    private ArrayList<JLabel> dealersHandGUI;

    /**
     * Creates new form BlackJackGameD
     */
    public BlackJackGameD(String dealerName, String playerName, boolean isPlayer, boolean isDealer) {
        initComponents();

        //Labels for the icons of Player Cards
        playersHandGUI = new ArrayList<javax.swing.JLabel>();
        playersHandGUI.add(pCard1Lbl);
        playersHandGUI.add(pCard2Lbl);
        playersHandGUI.add(pCard3Lbl);
        playersHandGUI.add(pCard4Lbl);
        playersHandGUI.add(pCard5Lbl);

        //Labels for the icons of Dealer Cards
        dealersHandGUI = new ArrayList<javax.swing.JLabel>();
        dealersHandGUI.add(dCard1Lbl);
        dealersHandGUI.add(dCard3Lbl);
        dealersHandGUI.add(dCard3Lbl);
        dealersHandGUI.add(dCard4Lbl);
        dealersHandGUI.add(dCard5Lbl);

        this.playerName = playerName;
        this.dealerName = dealerName;
        this.playerNameLbl.setText("Player: " + playerName);
        this.dealerNameLbl.setText("Dealer: " + dealerName);
        game = new BlackJack(playerName, dealerName, isPlayer, isDealer);
        game.newGame();
        playerCardsArr = new ArrayList<String>();
        playerCardsArr.add(game.getPlayer().getHand().get(0).toString());
        playerCardsArr.add(game.getPlayer().getHand().get(1).toString());
        dealerCardsArr = new ArrayList<String>();
        dealerCardsArr.add(game.getDealer().getHand().get(0).toString());
        dealerCardsArr.add(game.getDealer().getHand().get(1).toString());
        playersHandGUI.get(0).setIcon(new javax.swing.ImageIcon(getClass().getResource("Cards/" + getPlayerCardsArr().get(0) + ".png")));
        playersHandGUI.get(1).setIcon(new javax.swing.ImageIcon(getClass().getResource("Cards/" + getPlayerCardsArr().get(1) + ".png")));
        dealersHandGUI.get(0).setIcon(new javax.swing.ImageIcon(getClass().getResource("Cards/" + getDealerCardsArr().get(0) + ".png")));
        dealersHandGUI.get(1).setIcon(new javax.swing.ImageIcon(getClass().getResource("Cards/faceDown.png")));
        
        playerCards = game.getPlayer().getHand().toString();
        this.playerCardsLbl.setText("Cards: " + playerCards);
        playerScore = game.getPlayer().getScore();
        this.playerScoreLbl.setText("Score: " + playerScore);
        dealerCards = game.getDealer().getHand().toString();
        this.dealerCardsLbl.setText("Cards: " + dealerCards);
        dealerScore = game.getDealer().getScore();
        this.dealerScoreLbl.setText("Score: " + dealerScore);
        this.outcomeLbl.setVisible(false);
        this.againBtn.setVisible(false);
        this.menuBtn.setVisible(false);
//        Thread.sleep(800L);
        playerCards = game.getPlayer().getHand().toString();
        this.playerCardsLbl.setText("Cards: " + playerCards);
        playerScore = game.getPlayer().getScore();
        this.playerScoreLbl.setText("Score: " + playerScore);
        if (this.game.getPlayer().getScore() == 21) {
            JOptionPane.showMessageDialog(null, "You have won, player has exceeded 21", "Game outcome", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private BlackJackGameD() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBtn = new javax.swing.JButton();
        playerNameLbl = new javax.swing.JLabel();
        quitBtn = new javax.swing.JButton();
        dealerNameLbl = new javax.swing.JLabel();
        playerCardsLbl = new javax.swing.JLabel();
        dealBtn = new javax.swing.JButton();
        playerScoreLbl = new javax.swing.JLabel();
        dealerCardsLbl = new javax.swing.JLabel();
        dealerScoreLbl = new javax.swing.JLabel();
        stayBtn = new javax.swing.JButton();
        againBtn = new javax.swing.JButton();
        outcomeLbl = new javax.swing.JLabel();
        rulesBtn = new javax.swing.JButton();
        playerCardsPanel = new javax.swing.JPanel();
        pCard3Lbl = new javax.swing.JLabel();
        pCard1Lbl = new javax.swing.JLabel();
        pCard2Lbl = new javax.swing.JLabel();
        pCard4Lbl = new javax.swing.JLabel();
        pCard5Lbl = new javax.swing.JLabel();
        dealerCardsPanel = new javax.swing.JPanel();
        dCard1Lbl = new javax.swing.JLabel();
        dCard2Lbl = new javax.swing.JLabel();
        dCard3Lbl = new javax.swing.JLabel();
        dCard4Lbl = new javax.swing.JLabel();
        dCard5Lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menuBtn.setText("Return to Menu");
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });

        playerNameLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playerNameLbl.setText("Player Name:");

        quitBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        dealerNameLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dealerNameLbl.setText("Dealer Name:");

        playerCardsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        playerCardsLbl.setText("Player Cards:");

        dealBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dealBtn.setText("Deal");
        dealBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dealBtnActionPerformed(evt);
            }
        });

        playerScoreLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playerScoreLbl.setText("Score: ");

        dealerCardsLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dealerCardsLbl.setText("Dealer Cards:");

        dealerScoreLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dealerScoreLbl.setText("Score:");

        stayBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stayBtn.setText("Stay");
        stayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stayBtnActionPerformed(evt);
            }
        });

        againBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        againBtn.setText("Play Again?");
        againBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againBtnActionPerformed(evt);
            }
        });

        outcomeLbl.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        outcomeLbl.setText("Outcome");

        rulesBtn.setText("Rules");
        rulesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playerCardsPanelLayout = new javax.swing.GroupLayout(playerCardsPanel);
        playerCardsPanel.setLayout(playerCardsPanelLayout);
        playerCardsPanelLayout.setHorizontalGroup(
            playerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerCardsPanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(pCard2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(pCard3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pCard4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pCard5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(playerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(playerCardsPanelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(pCard1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(720, Short.MAX_VALUE)))
        );
        playerCardsPanelLayout.setVerticalGroup(
            playerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(playerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pCard3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(playerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pCard4Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(pCard5Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                        .addComponent(pCard2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(playerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(playerCardsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pCard1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout dealerCardsPanelLayout = new javax.swing.GroupLayout(dealerCardsPanel);
        dealerCardsPanel.setLayout(dealerCardsPanelLayout);
        dealerCardsPanelLayout.setHorizontalGroup(
            dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealerCardsPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(dCard3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dCard2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dCard4Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(dCard5Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
            .addGroup(dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dealerCardsPanelLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(dCard1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(734, Short.MAX_VALUE)))
        );
        dealerCardsPanelLayout.setVerticalGroup(
            dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dealerCardsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dCard4Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(dCard3Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addComponent(dCard2Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(dCard5Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
            .addGroup(dealerCardsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dealerCardsPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dCard1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerCardsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(quitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(againBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dealBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(stayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(rulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dealerNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dealerScoreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(outcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dealerCardsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerScoreLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(playerCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playerNameLbl)
                    .addComponent(quitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addComponent(playerScoreLbl)
                .addGap(2, 2, 2)
                .addComponent(playerCardsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(playerCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(againBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(dealerCardsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerCardsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dealerScoreLbl)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dealBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stayBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dealerNameLbl)
                    .addComponent(rulesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        BlackJackStartScreen menu = new BlackJackStartScreen();
        this.dispose();
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
    }//GEN-LAST:event_menuBtnActionPerformed

    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        JOptionPane.showMessageDialog(null, "Goodbye", "Game outcome", JOptionPane.PLAIN_MESSAGE);
        System.exit(0);
    }//GEN-LAST:event_quitBtnActionPerformed

    private void dealBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dealBtnActionPerformed
        // TODO add your handling code here:

        this.game.getDealer().getCard(this.game.getDeck().deal());
        dealerCards = game.getDealer().getHand().toString();
        this.dealerCardsLbl.setText("Cards: " + dealerCards);
        dealerScore = game.getDealer().getScore();
        this.dealerScoreLbl.setText("Score :" + dealerScore);
        if (this.game.getPlayer().getScore() > 21) {
            this.outcomeLbl.setText("Player has more than 21, you win");
            this.outcomeLbl.setVisible(true);
            this.againBtn.setVisible(true);
            this.menuBtn.setVisible(true);
        }

        if (this.game.getDealer().getScore() == 21 && this.game.getDealer().getScore() > this.game.getPlayer().getScore()) {
            this.outcomeLbl.setText("BlackJack!!!!! you have won");
            this.outcomeLbl.setVisible(true);
            this.againBtn.setVisible(true);
            this.menuBtn.setVisible(true);
        }
        if (this.game.getDealer().hasLost()) {
            String outcome = this.game.rulesD();
            this.outcomeLbl.setText(outcome);
            this.outcomeLbl.setVisible(true);
            this.againBtn.setVisible(true);
            this.menuBtn.setVisible(true);
            this.dealBtn.setVisible(false);
            this.stayBtn.setVisible(false);
        }


    }//GEN-LAST:event_dealBtnActionPerformed

    private void stayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stayBtnActionPerformed
        if (this.game.getPlayer().getScore() >= this.game.getDealer().getScore() && this.game.getPlayer().getScore() <= 21) {
            JOptionPane.showMessageDialog(null, "You cannot stay you have to beat the player.", "Game outcome", JOptionPane.WARNING_MESSAGE);
        } else {
            this.game.dealerAi();
            dealerCards = game.getDealer().getHand().toString();
            this.dealerCardsLbl.setText("Cards: " + dealerCards);
            dealerScore = game.getDealer().getScore();
            this.dealerScoreLbl.setText("Score: " + dealerScore);
            this.dealBtn.setVisible(false);
            this.stayBtn.setVisible(false);
            String outcome = this.game.rulesD();
            this.outcomeLbl.setText(outcome);
            this.outcomeLbl.setVisible(true);
            this.againBtn.setVisible(true);
            this.menuBtn.setVisible(true);
        }
    }//GEN-LAST:event_stayBtnActionPerformed

    private void againBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againBtnActionPerformed
        isPlayer = true;
        isDealer = false;
        BlackJackGameP game = new BlackJackGameP(dealerName, playerName, isPlayer, isDealer);
        JOptionPane.showMessageDialog(null, "Restarting game and inverting roles", "Game outcome", JOptionPane.PLAIN_MESSAGE);
        this.dispose();
        game.setLocationRelativeTo(null);
        game.setVisible(true);
    }//GEN-LAST:event_againBtnActionPerformed

    private void rulesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesBtnActionPerformed
        Rules rules = new Rules(this.game.getRules());
        rules.setVisible(true);
        rules.setLocationRelativeTo(null);
    }//GEN-LAST:event_rulesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackGameD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackGameD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackGameD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackGameD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJackGameD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton againBtn;
    private javax.swing.JLabel dCard1Lbl;
    private javax.swing.JLabel dCard2Lbl;
    private javax.swing.JLabel dCard3Lbl;
    private javax.swing.JLabel dCard4Lbl;
    private javax.swing.JLabel dCard5Lbl;
    private javax.swing.JButton dealBtn;
    private javax.swing.JLabel dealerCardsLbl;
    private javax.swing.JPanel dealerCardsPanel;
    private javax.swing.JLabel dealerNameLbl;
    private javax.swing.JLabel dealerScoreLbl;
    private javax.swing.JButton menuBtn;
    private javax.swing.JLabel outcomeLbl;
    private javax.swing.JLabel pCard1Lbl;
    private javax.swing.JLabel pCard2Lbl;
    private javax.swing.JLabel pCard3Lbl;
    private javax.swing.JLabel pCard4Lbl;
    private javax.swing.JLabel pCard5Lbl;
    private javax.swing.JLabel playerCardsLbl;
    private javax.swing.JPanel playerCardsPanel;
    private javax.swing.JLabel playerNameLbl;
    private javax.swing.JLabel playerScoreLbl;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton rulesBtn;
    private javax.swing.JButton stayBtn;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the playerCardsArr
     */
    public ArrayList<String> getPlayerCardsArr() {
        return playerCardsArr;
    }

    /**
     * @return the dealerCardsArr
     */
    public ArrayList<String> getDealerCardsArr() {
        return dealerCardsArr;
    }
}
